### ISSUE TITLE
Computer with only one GPU

### ISSUE THREAD

**Issue by mengnan12** [xwen99/temporal_context_aggregation#4]
Hi，thanks for your work，In your paper，you used 8 GPUs to train the network. I have only one GPU on my computer, So, how can I complete the train process with your code, that is how to run your code without using the **horovod** module. By the way, I want to know can Windows run the training code?

**Comment by xwen99** [comment]
Hi mengnan, thank you for your concern.
In fact, DDP modules like horovod also support single machine single GPU training, you can simply set the number of GPUs to one. Besides, if you are not familiar with horovod, you can switch to the default DDP module of PyTorch by modifying a few lines of code, please refer to the original [MoCo](https://github.com/facebookresearch/moco) repo for more implementation details.
About running on windows, I am not sure if PyTorch with cuda is well supported, and Linux is always recommended.
